name: deploy
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.6.0
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: '18'
      - run: cd compiler && ls -ls && npm install && npm update && npm test
      
